AWSTemplateFormatVersion: "2010-09-09"
Description: Cfn driver template to deploy resources on shared account
Parameters:
  project:
    Type: String
    Description: Project name
    Default: tgwShared
  env:
    Type: String
    AllowedValues: [dev, qa, uat, prod]
    Description: Environment name
    Default: dev
  app:
    Type: String
    Description: App name
    Default: app
  s3ArtifactPath:
    Type: String
    Default: "https://tgw-shared-blog-app-dev-us-east-1-576594342627.s3.amazonaws.com/code/cfn/services"
    Description: Artifact bucket path
Resources:
  vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/vpc/vpc-app.yaml"
      Parameters:
        project: !Ref project
        app: !Ref app
        env: !Ref env
        vpcCidrBlock: 10.30.0.0/16
        publicSubnet1CidrBlock: 10.30.0.0/20
        publicSubnet2CidrBlock: 10.30.16.0/20
        privateSubnet1CidrBlock: 10.30.128.0/20
        privateSubnet2CidrBlock: 10.30.144.0/20
        availabilityZone1: us-east-1a
        availabilityZone2: us-east-1b
        destinationCidrBlock: 0.0.0.0/0
        dnsHostnames: "true"
        dnsSupport: "true"
        mapPublicIp: "true"
      Tags:
        - Key: "project"
          Value: !Ref project
        - Key: "env"
          Value: !Ref env

  securityGroup:
    Type: AWS::CloudFormation::Stack
    DependsOn: vpc
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/sg/sg-app.yaml"
      Parameters:
        project: !Ref project
        app: !Ref app
        env: !Ref env
        ingressIpProtocol: tcp
        cidrIp: 0.0.0.0/0
        vpcId: !GetAtt vpc.Outputs.vpc
        sshPort: 22
        httpPort: 80
        httpsPort: 443
      Tags:
        - Key: "project"
          Value: !Ref project
        - Key: "env"
          Value: !Ref env

  apiEndpoint:
    Type: AWS::CloudFormation::Stack
    DependsOn: securityGroup
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/vpcendpoint/vpcendpoint-app.yaml"
      Parameters:
        env: !Ref env
        project: !Ref project
        vpcIdShared: !GetAtt vpc.Outputs.vpc
        VpcEndpointType: Interface
        securityGroups: !GetAtt securityGroup.Outputs.vpcEndpointSecurityGroup
        PrivateDnsEnabled: true
        privateSubnetIds: !Join
          - ","
          - - !GetAtt vpc.Outputs.privateSubnet1
            - !GetAtt vpc.Outputs.privateSubnet2
        app: app
      Tags:
        - Key: "project"
          Value: !Ref project
        - Key: "env"
          Value: !Ref env 

  transitGateway:
    Type: AWS::CloudFormation::Stack
    DependsOn: securityGroup
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/tgw/tgw-app.yaml"
      Parameters:
        project: !Ref project
        app: !Ref app
        env: !Ref env
        enableRouteTableAssociation: enable
        enableRouteTablePropagation: enable
        enableDnsSupport: enable
        enableMulticastSupport: disable
        enableVpnEcmpSupport: enable
        enableTgwAttachmentDnsSupport: enable
        privateTgwAttachmentSubnetIds: !Join
          - ","
          - - !GetAtt vpc.Outputs.privateSubnet1
            - !GetAtt vpc.Outputs.privateSubnet2
        TgwAttachmentVpcId: !GetAtt vpc.Outputs.vpc
      Tags:
        - Key: "project"
          Value: !Ref project
        - Key: "env"
          Value: !Ref env 

  twgRoute:
    DependsOn:
    - vpc
    - transitGateway
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/routeTable/rt-app.yml"
      Parameters:
        project: !Ref project
        app: !Ref app
        env: !Ref env
        privateRouteTable1: !GetAtt vpc.Outputs.privateRouteTable1
        privateRouteTable2: !GetAtt vpc.Outputs.privateRouteTable2
        publicRouteTable1: !GetAtt vpc.Outputs.publicRouteTable1
        publicRouteTable2: !GetAtt vpc.Outputs.publicRouteTable2
        sharedTgwID: !GetAtt transitGateway.Outputs.transitGatewayId
        consumerVpcCidrBlock: 10.40.0.0/16

  ram:
    Type: AWS::CloudFormation::Stack
    DependsOn: transitGateway
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/ram/ram-app.yaml"
      Parameters:
        project: !Ref project
        app: !Ref app
        env: !Ref env
        transitGatewayId: !GetAtt transitGateway.Outputs.transitGatewayId
        awsConsumerAccountId: 007756798683
      Tags:
        - Key: "project"
          Value: !Ref project
        - Key: "env"
          Value: !Ref env

  ec2:
    Type: AWS::CloudFormation::Stack
    DependsOn: ram
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/ec2/ec2-app.yaml"
      Parameters:
        ec2EnableEndpoint: yes #yes/no
        ec2EndpointIdentifier: !Sub "${project}-${env}-${app}-endpointConnect"
        ec2EndpointPreserveClientIp: true #true/false
        ec2EndpointPrivateSubnetId: !GetAtt vpc.Outputs.privateSubnet1
        ec2EndpointSgIds: !GetAtt securityGroup.Outputs.vpcEc2ConnectSecurityGroup
        project: !Ref project
        app: !Ref app
        env: !Ref env
        imageId: ami-066784287e358dad1
        availabilityZone: us-east-1a
        instanceType: t2.micro
        keyName: !Sub "${project}-${app}-${env}-${AWS::Region}-KP"
        securityGroupId: !GetAtt securityGroup.Outputs.ec2SecurityGroup
        subnetId: !GetAtt vpc.Outputs.privateSubnet1
        userDataText: Web Server
      Tags:
        - Key: "project"
          Value: !Ref project
        - Key: "env"
          Value: !Ref env
          
Outputs:
  vpc:
    Description: Shared Account VPC
    Value: !Ref vpc
    Export:
      Name: !Sub "${project}-${env}-vpc-${AWS::StackName}-${AWS::Region}"
  securityGroup:
    Description: Security Group
    Value: !Ref securityGroup
    Export:
      Name: !Sub "${project}-${env}-${app}-securityGroup-${AWS::StackName}-${AWS::Region}"
  apiEndpoint:
    Description: Api Endpoint
    Value: !Ref apiEndpoint
    Export:
      Name: !Sub "${project}-${env}-${app}-apiEndpoint-${AWS::StackName}-${AWS::Region}"
  transitGateway:
    Description: Transit Gateway
    Value: !Ref transitGateway
    Export:
      Name: !Sub "${project}-${env}-${app}-transitGateway-${AWS::StackName}-${AWS::Region}"
  ram:
    Description: Resource Access Manager
    Value: !Ref ram
    Export:
      Name: !Sub "${project}-${env}-${app}-ram-${AWS::StackName}-${AWS::Region}"
  ec2:
    Description: EC2 Instance
    Value: !Ref ec2
    Export:
      Name: !Sub "${project}-${env}-${app}-ec2-${AWS::StackName}-${AWS::Region}"
