AWSTemplateFormatVersion: '2010-09-09'
Description: Driver template to deploy security group
Parameters:
  project:
    Type: String
    Default: tgwsp
    Description: Project Name
  app:
    Type: String
    Default: app
    Description: App name
  env:
    Type: String
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Default: dev
    Description: Environment name
  s3ArtifactPath:
    Type: String
    Default: "https://tgw-sp-blog-app-dev-us-east-1-570720296911.s3.amazonaws.com/code/cfn/services"
    Description: "Artifact bucket path"
Resources:
  securitygroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/securitygroup/sg-app.yml"
      Parameters:
        project: !Ref project
        app: !Ref app
        env: !Ref env
        vpcIdServiceProvider: !GetAtt vpcServiceProvider.Outputs.vpc
       
Outputs:
 securitygroup:
  Value: !Ref securitygroup
  Export: 
    Name: !Sub "${project}-${app}-${env}-securitygroup"


 
 