AWSTemplateFormatVersion: 2010-09-09
Description: Template to deploy consumer VPC and it's components
Parameters:
  project:
    Type: String
    Description: Project Name
  app:
    Type: String
    Description: App name
  env:
    Type: String
    Description: Environment name
  publicRouteTable1:
    Type: String
    Default: ""
    Description: ID of the public route table 1
  publicRouteTable2:
    Type: String
    Default: ""
    Description: ID of the public route table 2
  privateRouteTable1:
    Type: String
    Default: ""
    Description: ID of the private route table 1
  privateRouteTable2:
    Type: String
    Default: ""
    Description: ID of the private route table 2
  sharedTgwID:
    Type: String
    Description: Id of the transit gateway attachment created in shared account
  consumerVpcCidrBlock:
    Type: String
    Description: IPv4 network range for the VPC created in consumer account

Resources:

  tgwPublicRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref publicRouteTable1
      DestinationCidrBlock: !Ref consumerVpcCidrBlock
      TransitGatewayId: !Ref sharedTgwID
  tgwPublicRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref publicRouteTable2
      DestinationCidrBlock: !Ref consumerVpcCidrBlock
      TransitGatewayId: !Ref sharedTgwID
  tgwPrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref privateRouteTable1
      DestinationCidrBlock: !Ref consumerVpcCidrBlock
      TransitGatewayId: !Ref sharedTgwID
  tgwPrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref privateRouteTable2
      DestinationCidrBlock: !Ref consumerVpcCidrBlock
      TransitGatewayId: !Ref sharedTgwID

  
Outputs:
  tgwPrivateRoute2:
    Description: twg for Private route2
    Value: !Ref tgwPrivateRoute2
    Export:
      Name: !Sub "${project}-${app}-${env}-tgwPrivateRoute2"
  tgwPrivateRoute1:
    Description: twg for Private route1
    Value: !Ref tgwPrivateRoute1
    Export:
      Name: !Sub "${project}-${app}-${env}-tgwPrivateRoute1"
  tgwPublicRoute2:
    Description: twg for Public route2
    Value: !Ref tgwPublicRoute2
    Export:
      Name: !Sub "${project}-${app}-${env}-tgwPublicRoute2"
  tgwPublicRoute1:
    Description: twg for Public route1
    Value: !Ref tgwPublicRoute1
    Export:
      Name: !Sub "${project}-${app}-${env}-tgwPublicRoute1"
  
