AWSTemplateFormatVersion: "2010-09-09"
Description: Template to deploy transit gateway
Parameters:
  project:
    Type: String
    Description: Project Name
  app:
    Type: String
    Description: App name
  env:
    Type: String
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Description: Environment name
  enableRouteTableAssociation:
    Type: String
    Default: enable
    AllowedValues: [enable, disable]
    Description: Enable or disable automatic association with the default association route table
  enableRouteTablePropagation:
    Type: String
    Default: enable
    AllowedValues: [enable, disable]    
    Description: Enable or disable automatic propagation of routes to the default propagation route table
  enableDnsSupport:
    Type: String
    Default: enable
    AllowedValues: [enable, disable]    
    Description: Enable or disable DNS support
  enableMulticastSupport:
    Type: String
    Default: enable
    AllowedValues: [enable, disable]
    Description: Enable or disable multicast support on the transit gateway
  enableVpnEcmpSupport:
    Type: String
    Default: enable
    AllowedValues: [enable, disable]
    Description: Enable or disable equal Cost multipath protocol support
  enableTgwAttachmentDnsSupport:
    Type: String
    Default: enable
    AllowedValues: [enable, disable]    
    Description: Enable or disable DNS support for transit gateway attachment
  privateTgwAttachmentSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The private subnet Ids for transit gateway attachment
  TgwAttachmentVpcId:
    Type: String
    Description: The VPC Id for transit gateway attachment
Resources:
  transitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
      Description: "The shared transit gateway"
      DefaultRouteTableAssociation: !Ref enableRouteTableAssociation
      DefaultRouteTablePropagation: !Ref enableRouteTablePropagation
      DnsSupport: !Ref enableDnsSupport
      MulticastSupport: !Ref enableMulticastSupport
      VpnEcmpSupport: !Ref enableVpnEcmpSupport
      Tags:
        - Key: Name
          Value: !Sub "${project}-${app}-${env}-transitGateway"
        - Key: project
          Value: !Ref project
        - Key: app
          Value: !Ref app
        - Key: environment
          Value: !Ref env
  transitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      Options: 
        DnsSupport: !Ref enableTgwAttachmentDnsSupport
      SubnetIds: !Ref privateTgwAttachmentSubnetIds
      TransitGatewayId: !Ref transitGateway
      VpcId: !Ref TgwAttachmentVpcId
      Tags:
        - Key: Name
          Value: !Sub "${project}-${app}-${env}-transitGatewayAttachment"
        - Key: project
          Value: !Ref project
        - Key: app
          Value: !Ref app
        - Key: environment
          Value: !Ref env
Outputs:
  transitGatewayId:
    Description: Transit Gateway Id
    Value: !Ref transitGateway
    Export:
      Name: !Sub "${project}-${app}-${env}-transitGatewayId"
  transitGatewayAttachment:
    Description: Transit Gateway Attachment Id
    Value: !Ref transitGatewayAttachment
    Export:
      Name: !Sub "${project}-${app}-${env}-transitGatewayAttachmentId"
