---
AWSTemplateFormatVersion: "2010-09-09"
Description: Driver template to deploy transit gateway
Parameters:
  project:
    Type: String
    Default: tgwBlogShared
    Description: Project Name
  app:
    Type: String
    Default: app
    Description: App name
  env:
    Type: String
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Default: dev
    Description: Environment name
  s3ArtifactPath:
    Type: String
    Default: "https://tgw-shared-blog-app-dev-us-east-1-576594342627.s3.amazonaws.com/code/cfn/services"
    Description: Artifact bucket path"
Resources:
  transitGateway:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/tgw/tgw-app.yaml"
      Parameters:
        project: !Ref project
        app: !Ref app
        env: !Ref env
        enableRouteTableAssociation: enable
        enableRouteTablePropagation: enable
        enableDnsSupport: enable
        enableMulticastSupport: disable
        enableVpnEcmpSupport: enable
        enableTgwAttachmentDnsSupport: enable
        privateTgwAttachmentSubnetIds: !Join
          - ","
          - - !GetAtt vpc.Outputs.privateSubnet1
            - !GetAtt vpc.Outputs.privateSubnet2
        TgwAttachmentVpcId: !GetAtt vpc.Outputs.vpc
Outputs:
  transitGateway:
    Description: Transit Gateway Stack
    Value: !Ref transitGateway
    Export:
      Name: !Sub "${project}-${app}-${env}-transitGatewayStack"

