AWSTemplateFormatVersion: "2010-09-09"
Description: Template to deploy transit gateway attachment
Parameters:
  project:
    Type: String
    Description: Project Name
  app:
    Type: String
    Description: App name
  env:
    Type: String
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Description: Environment name
  enableTgwAttachmentDnsSupport:
    Type: String
    Default: enable
    AllowedValues: [enable, disable]    
    Description: Enable or disable DNS support for transit gateway attachment
  privateTgwAttachmentSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The private subnet Ids for transit gateway attachment
  TgwAttachmentVpcId:
    Type: String
    Description: The VPC Id for transit gateway attachment
  transitGateway:
    Type: String
    Description: The transit gateway Id of shared account for transit gateway attachment
  
  
Resources:
  transitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      Options: 
        DnsSupport: !Ref enableTgwAttachmentDnsSupport
      SubnetIds: !Ref privateTgwAttachmentSubnetIds
      TransitGatewayId: !Ref transitGateway
      VpcId: !Ref TgwAttachmentVpcId
      Tags:
        - Key: Name
          Value: !Sub "${project}-${app}-${env}-transitGatewayAttachment"
        - Key: project
          Value: !Ref project
        - Key: app
          Value: !Ref app
        - Key: environment
          Value: !Ref env
Outputs:
  transitGatewayAttachment:
    Description: Transit Gateway Attachment Id
    Value: !Ref transitGatewayAttachment
    Export:
      Name: !Sub "${project}-${app}-${env}-transitGatewayAttachmentId"
