AWSTemplateFormatVersion: "2010-09-09"
Description: Template to deploy NLB
Parameters:
  project:
    Type: String
    Description: Project Name
  app:
    Type: String
    Description: App name
  env:
    Type: String
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Description: Environment name
  vpc:
    Type: AWS::EC2::VPC::Id
    Description: The vpc to launch the service
  subnet1:
    Type: AWS::EC2::Subnet::Id
    Description: first subnet where to launch the service
  subnet2:
    Type: AWS::EC2::Subnet::Id
    Description: second subnet where to Launch the service
  lbIpAddressType:
    Type: String
    Default: ipv4
    AllowedValues: [ipv4, dualstack]
    Description: Enter IP address Type, default ipv4
  name:
    Type: String
    Default: loadbalancer
    Description: Enter Load Balancer Name
  scheme:
    Type: String
    Default: internal
    AllowedValues: [internal, internet-facing]
    Description: Enter load balancer scheme , default internal
  elbType:
    Type: String
    Default: application
    AllowedValues: [application, gateway, network]
    Description: Enter load balancer type, default application
  deletionProtectionEnabled:
    Type: String
    Default: false
    AllowedValues: [false, true]
    Description: Enable Deletion Protection, default false 
  crossZoneLBEnabled:
    Type: String
    Default: false
    AllowedValues: [false, true]
    Description: Enable Cross Zone LB, default false
  tcpPort:
    Type: Number
    Default: 80
    MinValue: 1
    MaxValue: 65535
    Description: Enter http listener port, default 80
  tcpListenerDefaultActionType:
    Type: String
    Default: forward
    AllowedValues: [authenticate-cognito, authenticate-oidc, fixed-response, forward, redirect]
    Description: tcp listener default action type, default forward
  healthCheckEnabled:
    Type: String
    Default: true
    AllowedValues: [false, true]
    Description: Enable HealthCheck, default true 
  healthCheckIntervalSeconds:
    Type: Number
    Default: 30
    MinValue: 5
    MaxValue: 300
    Description: Enter HealthCheck interval, default 30
  healthCheckPort:
    Type: String
    Default: "traffic-port"
    Description: Enter HealthCheck port, default traffic-port
  nlbHealthCheckProtocol:
    Type: String
    Default: TCP
    AllowedValues: [TCP, TCP_UDP, TLS, UDP, HTTP, HTTPS]
    Description: Enter HealthCheck Protocol, default TCP 
  healthCheckTimeoutSeconds:
    Type: Number
    Default: 10
    MinValue: 2
    MaxValue: 120
    Description: Enter HealthCheck timeout, default 10
  healthyThresholdCount:
    Type: Number
    Default: 3
    MinValue: 2
    MaxValue: 10
    Description: Enter healthy threshold count, default 3
  ipAddressType:
    Type: String
    Default: ipv4
    AllowedValues: [ipv4, ipv6]
    Description: Enter ip address type, default ipv4 
  nlbTargetPort:
    Type: Number
    Default: 80
    MinValue: 1
    MaxValue: 65535
    Description: Enter target port, default 80
  nlbTargetProtocol:
    Type: String
    Default: TCP
    AllowedValues: [TCP, TLS, TCP_UDP, UDP]
    Description: Enter target protocol, default TCP
  targetType:
    Type: String
    Default: instance
    AllowedValues: [alb, instance, ip, lambda]
    Description: Enter target type, default instance
  stickinessEnabled:
    Type: String
    Default: false
    AllowedValues: [false, true]
    Description: Enable Stickiness, default false
  targetDeregistrationDelay:
    Type: Number
    Default: 300
    MinValue: 0
    MaxValue: 3600
    Description: Enter target deregistration delay, default 300
  deregistrationConnectionTerminationEnabled:
    Type: String
    Default: false
    AllowedValues: [false, true]
    Description: Enable deregistration connection termination, default false 
  preserveClientIPEnabled:
    Type: String
    Default: true
    AllowedValues: [false, true]
    Description: Enable preserve client ip, default true 
  proxyProtocolV2Enabled:
    Type: String
    Default: false
    AllowedValues: [false, true]
    Description: Enable proxy protocol v2, default false 
  targetResource1Port:
    Type: String
    Default: "80"
    Description: Enter target group resource1 Port
  targetResourceId:
    Type: String
    Default: ""
    Description: Enter target group resource ID
  sgNetworklb:
    Type: String
    Default: ""
    Description: Enter the network security group


Resources:            
    networkLoadBalancer:
      Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
      Properties:
        IpAddressType: !Ref lbIpAddressType
        LoadBalancerAttributes:
          - Key: "deletion_protection.enabled"
            Value: !Ref deletionProtectionEnabled
          - Key: "load_balancing.cross_zone.enabled"
            Value: !Ref crossZoneLBEnabled
        Name: !Ref name
        Scheme: !Ref scheme
        Subnets: 
          - !Ref subnet1
          - !Ref subnet2
        SecurityGroups:  
          - !Ref sgNetworklb
        Tags:
          - Key: Name
            Value: !Sub "${project}-${app}-${env}-nlb"
          - Key: project
            Value: !Ref project
          - Key: app
            Value: !Ref app
          - Key: environment
            Value: !Ref env
        Type: !Ref elbType

    tcpListener:
      Type: "AWS::ElasticLoadBalancingV2::Listener"
      Properties:
        DefaultActions: 
          - Order: 20
            ForwardConfig:
              TargetGroups:
                - TargetGroupArn: !Ref targetGroup
            Type: !Ref tcpListenerDefaultActionType
        LoadBalancerArn: !Ref networkLoadBalancer
        Port: !Ref tcpPort
        Protocol: TCP  

    targetGroup:
      Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
      Properties:
        HealthCheckEnabled: !Ref healthCheckEnabled
        HealthCheckIntervalSeconds: !Ref healthCheckIntervalSeconds
        HealthCheckPort: !Ref healthCheckPort
        HealthCheckProtocol: !Ref nlbHealthCheckProtocol
        HealthCheckTimeoutSeconds: !Ref healthCheckTimeoutSeconds
        HealthyThresholdCount: !Ref healthyThresholdCount
        IpAddressType: !Ref ipAddressType
        Name: !Sub "${project}-${env}-tg-${app}-${nlbTargetPort}"
        Port: !Ref nlbTargetPort
        Protocol: !Ref nlbTargetProtocol
        Tags:
          - Key: Name
            Value: !Sub "${project}-${app}-${env}-nlb-tg-tcp"
          - Key: project
            Value: !Ref project
          - Key: app
            Value: !Ref app
          - Key: environment
            Value: !Ref env
        TargetGroupAttributes:                            
          - Key: "deregistration_delay.timeout_seconds"
            Value: !Ref targetDeregistrationDelay
          - Key: "stickiness.enabled"
            Value: !Ref stickinessEnabled
          - Key: "deregistration_delay.connection_termination.enabled"
            Value: !Ref deregistrationConnectionTerminationEnabled          
          - Key: "preserve_client_ip.enabled"
            Value: !Ref preserveClientIPEnabled
          - Key: "proxy_protocol_v2.enabled"
            Value: !Ref proxyProtocolV2Enabled
        Targets: 
          - Id: !Ref targetResourceId
            Port: !Ref targetResource1Port
        TargetType: !Ref targetType
        VpcId: !Ref vpc
   
Outputs:          
    nlb:
      Value: !Ref networkLoadBalancer
      Export:
        Name: !Sub "${project}-${env}-${app}-nlb-arn"
    nlbDns:
      Value: !GetAtt networkLoadBalancer.DNSName
      Export:
        Name: !Sub "${project}-${env}-${app}-nlb-dns"
    targetGroup:
      Value: !Ref targetGroup
      Export:
        Name: !Sub "${project}-${env}-${app}-nlb-tg-arn"


