AWSTemplateFormatVersion: "2010-09-09"
Description: Template to deploy Resource Access Manager
Parameters:
  project:
    Type: String
    Description: Project Name
  app:
    Type: String
    Description: App name
  env:
    Type: String
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Description: Environment name
  transitGatewayId:
    Type: String
    Description: The transit gateway ARN for resource sharing
  awsConsumerAccountId:
    Type: String
    Description: The AWS consumer account Id
Resources:
  ram:
    Type: AWS::RAM::ResourceShare
    Properties:
      Name: !Sub "${project}-${app}-${env}-ram"
      ResourceArns: 
        - !Sub arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:transit-gateway/${transitGatewayId}
      Principals: 
        - !Ref awsConsumerAccountId
      Tags:
        - Key: Name
          Value: !Sub "${project}-${app}-${env}-ram"
        - Key: project
          Value: !Ref project
        - Key: app
          Value: !Ref app
        - Key: environment
          Value: !Ref env
Outputs:
  ram:
    Description: RAM Resource Shared Id
    Value: !Ref ram
    Export:
      Name: !Sub "${project}-${app}-${env}-ram"
