---
AWSTemplateFormatVersion: "2010-09-09"
Description: Driver template to deploy EC2
Parameters:
  project:
    Type: String
    Default: tgwconsumer
    Description: Project Name
  app:
    Type: String
    Default: app
    Description: App name
  env:
    Type: String
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Default: dev
    Description: Environment name
  s3ArtifactPath:
    Type: String
    Default: "https://tgw-consumer-blog-app-dev-us-east-1-007756798683.s3.amazonaws.com/code/cfn/services"
    Description: Artifact bucket path"
Resources:
  ec2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/ec2/ec2-app.yaml"
      Parameters:
        ec2EnableEndpoint: yes #yes/no
        ec2EndpointIdentifier: !Sub "${project}-${env}-${app}-endpointConnect"
        ec2EndpointPreserveClientIp: true #true/false
        ec2EndpointPrivateSubnetId: !GetAtt vpc.Outputs.publicSubnet1
        ec2EndpointSgIds: !GetAtt securityGroup.Outputs.vpcEc2ConnectSecurityGroup
        project: !Ref project
        app: !Ref app
        env: !Ref env
        imageId: ami-03972092c42e8c0ca
        availabilityZone: us-east-1a
        instanceType: t2.micro
        keyName: !Sub "${project}-${app}-${env}-${AWS::Region}-KP"
        securityGroupId: !GetAtt securityGroup.Outputs.securityGroup
        subnetId: !GetAtt vpc.Outputs.privateSubnet1
        
Outputs:
  ec2Stack:
    Description: EC2 Stack
    Value: !Ref ec2
    Export:
      Name: !Sub "${project}-${app}-${env}-ec2Stack"
