AWSTemplateFormatVersion: "2010-09-09"
Description: Driver template to deploy consumer VPC
Parameters:
  project:
    Type: String
    Default: tgwconsumer
    Description: Project Name
  app:
    Type: String
    Default: app
    Description: App name
  env:
    Type: String
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Default: dev
    Description: Environment name
  s3ArtifactPath:
    Type: String
    Default: "https://tgw-consumer-blog-app-dev-us-east-1-007756798683.s3.amazonaws.com/code/cfn/services"
    Description: "Artifact bucket path"
Resources:
  vpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/vpc/vpc-app.yaml"
      Parameters:
        project: !Ref project
        app: !Ref app
        env: !Ref env
        vpcCidrBlock: 10.40.0.0/16
        publicSubnet1CidrBlock: 10.40.0.0/20
        publicSubnet2CidrBlock: 10.40.16.0/20
        privateSubnet1CidrBlock: 10.40.128.0/20
        privateSubnet2CidrBlock: 10.40.144.0/20
        availabilityZone1: us-east-1a
        availabilityZone2: us-east-1b
        destinationCidrBlock: 0.0.0.0/0
        dnsHostnames: "true"
        dnsSupport: "true"
        mapPublicIp: "true"
        # shareTransitGatewayId: tgw-1234567
        # sharedVpcCidrBlock: 10.x.x.x/x
Outputs:
  vpcStack:
    Description: Vpc consumer Stack
    Value: !Ref vpc
    Export:
      Name: !Sub "${project}-${app}-${env}-vpcStack"
