AWSTemplateFormatVersion: 2010-09-09
Description: Template to deploy api gateway vpc link
Parameters:
  project:
    Type: String
    Description: Project Name
  app:
    Type: String
    Description: App name
  env:
    Type: String
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Description: Environment name
  TargetArns:
    Type: String
    Description: The ARN of network load balancer of the VPC targeted by the VPC link

Resources:
  apiGatewayVpcLink:
        Type: "AWS::ApiGateway::VpcLink"
        Properties:
            Name: !Sub "${project}-${env}-${app}-vpclink"
            Tags:
              - Key: Name
                Value: !Sub "${project}-${app}-${env}-privatelink"
              - Key: project
                Value: !Ref project
              - Key: app
                Value: !Ref app
              - Key: environment
                Value: !Ref env
            TargetArns: 
              - !Ref TargetArns

Outputs:
  apiGatewayVpcLinkId:
    Value: !Ref apiGatewayVpcLink
    Export:
      Name: !Sub "${project}-${env}-${app}-apiGatewayVpcLinkId"