AWSTemplateFormatVersion: 2010-09-09
Description: "Template to deploy Interface VPC Endpoint "
Parameters:
  project:
    Type: String
    Description: Name of the Project
  env:
    Type: String
    AllowedValues:
      - dev
      - qa
      - uat
      - prod
    Description: Environment name
  app:
    Type: String
    Default: app
    Description: Name of the app
  vpcIdShared:
    Type: String
    Description: The shared VPC Id
  VpcEndpointType:
    Type: String
    Description: The type of endpoint
  securityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: The EC2 security group
  privateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The private subnet IDs
  PrivateDnsEnabled:
    Type: String
    Description: Indicate whether to associate a private hosted zone with the specified VPC
Resources:
# api endpoint
  apiEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref vpcIdShared
      PrivateDnsEnabled: !Ref PrivateDnsEnabled
      VpcEndpointType: !Ref VpcEndpointType
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.execute-api"
      SubnetIds: !Ref privateSubnetIds
      SecurityGroupIds: !Ref securityGroups
Outputs:
  apiEndpoint:
    Value: !Ref apiEndpoint
    Export:
      Name: !Sub "${project}-${env}-${app}-${AWS::Region}-apiEndpoint"